# ./docker-compose.yml

version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - /home/ubuntu/ELK_data/elasticsearch:/usr/share/elasticsearch/data:rw
    hostname: elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
    - ELK
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    hostname: kibana
    depends_on:
    - elasticsearch
    ports:
      - "5601:5601"
    networks:
    - ELK
  logstash:
    image: docker.elastic.co/logstash/logstash:6.3.2
    depends_on:
    - elasticsearch
    volumes:
      - /home/ubuntu/ELK_data/logstash/csv:/shared:rw
    hostname: logstash
    networks:
    - ELK

networks:
  ELK:
    driver: "bridge"
